name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # - name: Navigate to backend directory
    #   run: cd backend
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      env:
        DB_HOST: ${{secrets.DB_HOST}}
        DB_NAME: ${{secrets.DB_NAME}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_PORT: ${{secrets.DB_PORT}}
      run: docker build --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                    --build-arg DB_NAME=${{ secrets.DB_NAME }} \
                    --build-arg DB_USER=${{ secrets.DB_USER }} \
                    --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                    --build-arg DB_PORT=${{ secrets.DB_PORT }} \
                    -t hoangnv99/teamfab-backend-2 backend/.
    
    - name: Push to Dockerhub
      run: docker push hoangnv99/teamfab-backend-2:latest
