name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      
    - name: Build the Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          --build-arg DB_HOST=${{ secrets.DB_HOST }} \
          --build-arg DB_NAME=${{ secrets.DB_NAME }} \
          --build-arg DB_USER=${{ secrets.DB_USER }} \
          --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --build-arg DB_PORT=${{ secrets.DB_PORT }} \
          -t hoangnv99/teamfab-backend-2:latest backend/. --push

    - name: Push to Dockerhub
      run: docker push hoangnv99/teamfab-backend-2:latest
